config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :mousaillons

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mousaillon.rb
class Mousaillon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
  	render html: "Hello World"
  end
end

app/controllers/mousaillons_controller.rb
class MousaillonsController < ApplicationController
	def new
		@mousaillons = Mousaillon.new
	end

	def create
		post = Mousaillon.create(post_params)
		redirect_to mousaillon_path(post.id)
	end

	def show 
		@mousaillons = Mousaillon.find(params[:id])
	end

	def index
		@mousaillons = Mousaillon.all
	end

	def edit
		@mousaillons = Mousaillon.find(params[:id])
	end

	def update
		@mousaillons = Mousaillon.find(params[:id])
		@mousaillons.update(post_params)
		redirect_to mousaillons_path
	end

	def destroy
		@mousaillons = Mousaillon.find(params[:id])
		@mousaillons.destroy
		redirect_to mousaillons_path
	end

	private
	def post_params
		params.require(:mousaillon).permit(:username, :email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mousaillons_helper.rb
module MousaillonsHelper
end

app/helpers/moussaillons_helper.rb
module MoussaillonsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MousaillonSamere</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mousaillons/edit.html.erb
<h1>Edit ton profil</h1>

<%= form_for @mousaillons do |f| %>
	<div class='beau'>
	<label>Username</label>
	  <%= f.text_field :username %>
	</div>
	<div class='beau'>
		<label>Email</label>
  	  <%= f.text_field :email %>
	</div>
	<div class='beau'>
		<label>bio</label>
  	  <%= f.text_field :bio %>
	</div>
  	<div>
 		<%= f.submit "Create" %>
 	</div>
<% end %>

app/views/mousaillons/index.html.erb
<h1>Mousaillons#index</h1>
<p>Find me in app/views/mousaillons/index.html.erb</p>

app/views/mousaillons/new.html.erb
<h1>Crée toi un compte Mousaillon avec un seul S !</h1>

<%= form_for @mousaillons do |f| %>
	<div class='geronimo'>
	<label>Username ? </label>
	  <%= f.text_field :username %>
	</div>
	<div class='geronimo'>
		<label>Email ?</label>
  	  <%= f.text_field :email %>
	</div>
  	<div>
 		<%= f.submit "Fait toi plaiz !" %>
 	</div>
<% end %>

app/views/mousaillons/show.html.erb
<h2>Voici ton compte jeune Mousaillon ! </h2>

<table>
	<tr>
		<th>Username</th>
		<th>Email</th>
	</tr>
	<tr>
		<td><%= @mousaillons.username %>
		</td>
		<td><%= @mousaillons.email%></td>
	</tr>
<%= link_to 'Va voir lindex super cool', edit_mousaillon_path%>

</table>